angle_entity_trail_list:
    path: /
    controller: Angle\EntityTrailBundle\Controller\EntityTrailLogController::list
    methods: GET

angle_entity_trail_data:
    path: /data
    controller: Angle\EntityTrailBundle\Controller\Ajax\EntityTrailLogController::data
    methods: POST

angle_entity_trail_view:
    path: /{code}
    controller: Angle\EntityTrailBundle\Controller\EntityTrailLogController::view
    methods: GET
